-- MySQL Script generated by MySQL Workbench
-- Thu Nov  5 19:00:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tpu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpu` DEFAULT CHARACTER SET utf8 ;
USE `tpu` ;

-- -----------------------------------------------------
-- Table `tpu`.`regiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpu`.`regiones` (
  `codigo` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(60) NULL,
  `codigo_supregion` VARCHAR(11) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_regiones_regiones1_idx` (`codigo_supregion` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tpu`.`conteos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpu`.`conteos` (
  `idConteo` INT NOT NULL AUTO_INCREMENT,
  `codigo_agrupacion` VARCHAR(11) NOT NULL,
  `nombre_agrupacion` VARCHAR(60) NULL,
  `codigo_region` VARCHAR(11) NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idConteo`),
  INDEX `fk_conteos_regiones1_idx` (`codigo_region` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;